/**
 * 모든 화면 문구(UX-01). 컴포넌트는 문구를 직접 쓰지 않고 이 파일의 키만 참조한다.
 * 오류 문구는 원인과 해결 방법을 함께 안내한다(UX-03).
 */
export const S = {
  app: { name: 'MeetLite', tagline: '설치 없이, 링크 하나로 바로 만나는 화상회의' },
  landing: {
    title: '링크 하나로 바로 시작하세요',
    subtitle: '설치도 가입도 필요 없습니다. 방을 만들고 링크를 공유하면 끝입니다.',
    nicknameLabel: '닉네임',
    nicknamePlaceholder: '회의에서 보일 이름',
    nicknameHint: '1~20자, 한글·영문·숫자·공백·_ - . 만 쓸 수 있습니다.',
    createButton: '새 회의 만들기',
    creating: '만드는 중…',
    passwordToggle: '비밀번호 설정 (선택)',
    passwordLabel: '방 비밀번호',
    passwordHint: '4~32자. 참가자에게 따로 알려 주세요. 링크에는 들어가지 않습니다.',
    joinTitle: '초대 링크가 있나요?',
    joinPlaceholder: '링크 또는 방 코드 붙여넣기',
    joinButton: '입장',
    joinInvalid: '올바른 회의 링크가 아닙니다. 받은 링크를 그대로 붙여넣어 주세요.',
    support: 'Chrome, Edge, Firefox, Safari 최신 버전을 지원합니다. 화면공유는 PC 브라우저에서만 쓸 수 있습니다.',
  },
  lobby: {
    title: '입장 전 확인',
    previewLabel: '내 카메라 미리보기',
    cameraOff: '카메라가 꺼져 있습니다',
    mic: '마이크',
    camera: '카메라',
    speaker: '스피커',
    micLevel: '마이크 입력 레벨',
    noDevice: '장치 없음',
    privacy: '영상 통화를 연결하는 과정에서 다른 참가자에게 내 네트워크 정보(IP 주소 등)가 보일 수 있습니다.',
    join: '회의 입장',
    joining: '입장하는 중…',
    joinWithoutDevices: '장치 없이 입장',
    copyLink: '초대 링크 복사',
    copied: '링크를 복사했습니다',
    copyFailed: '자동 복사에 실패했습니다. 아래 링크를 직접 선택해 복사해 주세요.',
    nicknameLabel: '닉네임',
    passwordLabel: '방 비밀번호',
    wrongPassword: '비밀번호가 맞지 않습니다. 호스트에게 비밀번호를 다시 확인해 주세요.',
    tooManyAttempts: '비밀번호를 여러 번 틀려 잠시 입장할 수 없습니다. 10분 뒤에 다시 시도해 주세요.',
    invalidNickname: '닉네임은 1~20자이고 한글·영문·숫자·공백·_ - . 만 쓸 수 있습니다.',
    rateLimited: '요청이 너무 많습니다. 잠시 뒤에 다시 시도해 주세요.',
    hostBadge: '호스트로 입장합니다',
    permissionNote: '카메라와 마이크 권한을 허용하면 미리보기가 나타납니다.',
    cancel: '처음으로',
  },
  room: {
    mute: '마이크 끄기',
    unmute: '마이크 켜기',
    cameraOn: '카메라 켜기',
    cameraOffAction: '카메라 끄기',
    controls: '회의 컨트롤',
    stage: '회의 화면',
    micLabel: '마이크',
    cameraLabel: '카메라',
    shareLabel: '화면공유',
    shareStop: '공유 중지',
    chat: '채팅',
    participants: '참가자',
    leave: '나가기',
    copyLink: '링크 복사',
    deviceMenuMic: '마이크 장치 선택',
    deviceMenuCamera: '카메라 장치 선택',
    you: '(나)',
    host: '호스트',
    sharingNow: (name: string) => `${name}님이 화면을 공유 중입니다`,
    youSharing: '내 화면을 공유 중입니다',
    shareUnsupportedMobile: '모바일 브라우저에서는 화면공유를 지원하지 않습니다. PC 브라우저를 이용해 주세요.',
    shareBusy: (name: string) => `${name}님이 이미 화면을 공유 중입니다. 공유가 끝난 뒤에 시작해 주세요.`,
    shareDenied: '화면공유가 취소되었거나 권한이 없습니다. 다시 시도해 주세요.',
    micMutedByHost: '호스트가 모든 참가자의 마이크를 껐습니다. 말하려면 마이크를 다시 켜 주세요.',
    locked: '방이 잠겨 있습니다',
    alone: '아직 아무도 없어요',
    aloneHint: '링크를 복사해서 참가자를 초대해 보세요.',
    peerProblem: '연결 문제',
    cameraIsOff: '카메라 꺼짐',
    live: '연결됨',
    reconnecting: '재연결 중',
    poor: '불안정',
    poorBanner: '네트워크가 불안정합니다. 카메라를 끄면 개선될 수 있습니다.',
    reconnectingBanner: '연결이 끊겨 다시 연결하는 중입니다. 자리는 잠시 유지됩니다.',
    joined: (name: string) => `${name}님이 입장했습니다`,
    left: (name: string) => `${name}님이 나갔습니다`,
    timedOut: (name: string) => `${name}님의 연결이 끊겨 퇴장 처리되었습니다`,
    hostChanged: (name: string) => `${name}님이 새 호스트가 되었습니다`,
    youAreHost: '이제 내가 호스트입니다',
    lockedToast: '방을 잠갔습니다. 새 참가자는 입장할 수 없습니다',
    unlockedToast: '방 잠금을 해제했습니다',
    reconnected: '다시 연결되었습니다',
    deviceChangeFailed: '장치를 바꾸지 못했습니다. 다른 앱이 장치를 사용 중인지 확인해 주세요.',
    cameraFailed: '카메라를 켜지 못했습니다. 브라우저 권한과 다른 앱의 사용 여부를 확인해 주세요.',
    micFailed: '마이크를 켜지 못했습니다. 브라우저 권한과 다른 앱의 사용 여부를 확인해 주세요.',
    actionFailed: '요청을 처리하지 못했습니다. 잠시 뒤에 다시 시도해 주세요.',
    forbidden: '호스트만 할 수 있는 기능입니다.',
  },
  chat: {
    title: '채팅',
    placeholder: '메시지 입력 (최대 500자)',
    send: '보내기',
    empty: '첫 메시지를 보내 보세요',
    emptyHint: '대화는 서버에 저장되지 않고, 이 방이 끝나면 사라집니다.',
    tooLong: '메시지는 500자까지 보낼 수 있습니다.',
    rateLimited: '너무 빨리 보내고 있습니다. 잠시 뒤에 다시 보내 주세요.',
    failed: '메시지를 보내지 못했습니다. 연결 상태를 확인해 주세요.',
    counter: (n: number) => `${n}/500`,
    close: '채팅 닫기',
    newMessages: '새 메시지',
  },
  people: {
    title: '참가자',
    close: '참가자 목록 닫기',
    lock: '방 잠그기',
    unlock: '방 잠금 해제',
    muteAll: '전체 음소거',
    kick: '내보내기',
    hostOnly: '호스트 도구',
    micOn: '마이크 켜짐',
    micOff: '마이크 꺼짐',
    camOn: '카메라 켜짐',
    camOff: '카메라 꺼짐',
    sharing: '화면 공유 중',
    reconnecting: '재연결 중',
    count: (n: number) => `참가자 ${n}명`,
  },
  confirm: {
    cancel: '취소',
    leaveTitle: '회의에서 나갈까요?',
    leaveBody: '나가도 같은 링크로 다시 입장할 수 있습니다. 호스트가 나가면 가장 먼저 들어온 참가자가 호스트가 됩니다.',
    leaveConfirm: '나가기',
    kickTitle: (name: string) => `${name}님을 내보낼까요?`,
    kickBody: '내보낸 참가자는 이 방에 다시 들어올 수 없습니다.',
    kickConfirm: '내보내기',
    muteAllTitle: '모든 참가자의 마이크를 끌까요?',
    muteAllBody: '호스트를 제외한 모두의 마이크가 꺼집니다. 각자 다시 켤 수 있습니다.',
    muteAllConfirm: '전체 음소거',
  },
  devices: {
    title: '장치 설정',
    close: '닫기',
    mic: '마이크',
    camera: '카메라',
    speaker: '스피커',
    none: '선택 가능한 장치가 없습니다',
    default: '기본 장치',
    speakerUnsupported: '이 브라우저는 스피커 선택을 지원하지 않습니다. 기기 설정에서 바꿔 주세요.',
  },
  state: {
    loading: { title: '준비하는 중입니다', body: '잠시만 기다려 주세요.', slow: '연결이 오래 걸리고 있습니다. 네트워크를 확인하고 다시 시도해 주세요.' },
    error: {
      title: '문제가 발생했습니다',
      body: '서버와 통신하지 못했습니다. 인터넷 연결을 확인한 뒤 다시 시도해 주세요.',
      retry: '다시 시도',
      home: '처음으로',
    },
    permission: {
      title: '카메라·마이크를 사용할 수 없습니다',
      denied: '카메라 또는 마이크 권한이 차단되었습니다. 주소창의 자물쇠 아이콘에서 허용한 뒤 새로고침해 주세요.',
      notFound: '연결된 카메라나 마이크를 찾지 못했습니다. 장치가 연결되어 있는지 확인해 주세요. 장치 없이도 입장할 수 있습니다.',
      inUse: '다른 앱이 카메라나 마이크를 사용 중입니다. 해당 앱을 닫은 뒤 다시 확인해 주세요.',
      unknown: '장치를 시작하지 못했습니다. 브라우저를 새로고침하거나 다른 브라우저로 시도해 주세요.',
      retry: '다시 확인',
    },
    full: { title: '방이 가득 찼습니다', body: '이 방은 정원이 가득 찼습니다. 호스트에게 문의하거나 잠시 뒤에 다시 시도해 주세요.', retry: '다시 시도' },
    locked: { title: '방이 잠겨 있습니다', body: '호스트가 새 참가자의 입장을 막았습니다. 호스트에게 잠금 해제를 요청해 주세요.', retry: '다시 시도' },
    kicked: { title: '회의에서 내보내졌습니다', body: '호스트가 이 회의에서 내보냈습니다. 필요하다면 호스트에게 문의해 주세요.', home: '처음으로' },
    gone: {
      title: '회의를 찾을 수 없습니다',
      closed: '이미 종료되었거나 만료된 회의입니다. 링크를 다시 확인하거나 새 회의를 만들어 주세요.',
      restarted: '서비스가 재시작되어 회의가 종료되었습니다. 새 회의를 만들어 다시 시작해 주세요.',
      newRoom: '새 회의 만들기',
    },
    unsupported: {
      title: '이 브라우저에서는 사용할 수 없습니다',
      body: '화상회의에 필요한 기능(WebRTC, 카메라 접근)을 지원하지 않거나 보안 연결(HTTPS)이 아닙니다. 최신 Chrome, Edge, Firefox, Safari에서 열어 주세요.',
      copy: '링크 복사해서 다른 브라우저에서 열기',
    },
    left: { title: '회의에서 나왔습니다', body: '필요하면 같은 링크로 다시 입장할 수 있습니다.', rejoin: '다시 입장', home: '처음으로' },
    expired: {
      title: '연결이 오래 끊겨 회의에서 나갔습니다',
      body: '네트워크가 복구되지 않아 자리가 정리되었습니다. 다시 입장해 주세요.',
      rejoin: '다시 입장',
    },
    waitHost: { title: '호스트를 기다리고 있습니다', body: '호스트가 입장하면 자동으로 시작됩니다. 이 화면을 닫지 마세요.', cancel: '처음으로' },
  },
} as const;

/** 서버 오류 코드 → 사용자 안내 문구 */
export const errorText = (code: string): string => {
  switch (code) {
    case 'RATE_LIMITED':
      return S.lobby.rateLimited;
    case 'FORBIDDEN':
      return S.room.forbidden;
    case 'INVALID_PAYLOAD':
      return S.lobby.invalidNickname;
    default:
      return S.room.actionFailed;
  }
};
